### ISSUE TITLE
some times may get java.util.NoSuchElementException while execute query

### ISSUE THREAD

**Issue by oOKevinOo** [yaooqinn/kyuubi#142]
erro like fellow:
Current operation state RUNNING,
java.util.NoSuchElementException
        at java.util.concurrent.ConcurrentHashMap$ValueIterator.next(ConcurrentHashMap.java:3436)
        at org.apache.spark.SparkEnv$.get(SparkEnv.scala:165)
        at org.apache.spark.util.Utils$.maxNumToStringFields(Utils.scala:95)
        at org.apache.spark.util.Utils$.truncatedString$default$5(Utils.scala:116)
        at org.apache.spark.util.Utils$.truncatedString(Utils.scala:132)
        at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$output$1(QueryExecution.scala:218)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$3.apply(QueryExecution.scala:221)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$3.apply(QueryExecution.scala:221)
        at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:107)
        at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:221)
        at yaooqinn.kyuubi.operation.KyuubiOperation$$anonfun$yaooqinn$kyuubi$operation$KyuubiOperation$$execute$3.apply(KyuubiOperation.scala:319)
        at yaooqinn.kyuubi.operation.KyuubiOperation$$anonfun$yaooqinn$kyuubi$operation$KyuubiOperation$$execute$3.apply(KyuubiOperation.scala:319)
        at scala.Option.foreach(Option.scala:257)
        at yaooqinn.kyuubi.operation.KyuubiOperation.yaooqinn$kyuubi$operation$KyuubiOperation$$execute(KyuubiOperation.scala:318)
        at yaooqinn.kyuubi.operation.KyuubiOperation$$anon$1$$anon$2.run(KyuubiOperation.scala:274)
        at yaooqinn.kyuubi.operation.KyuubiOperation$$anon$1$$anon$2.run(KyuubiOperation.scala:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
        at yaooqinn.kyuubi.operation.KyuubiOperation$$anon$1.run(KyuubiOperation.scala:270)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

is that modify SparkEnv class code caused such erro?

**Comment by yaooqinn** [comment]
Yes, you're right. Which version are you using? This might be fixed by https://github.com/yaooqinn/kyuubi/commit/d4b9d61ea4b1b8811bc0d7efef951a44e4f49c51

**Comment by oOKevinOo** [comment]
i using 0.4.0 release version now,and i see the code is same as d4b9d61 related.
i reviewed the code,it caused by env ConcurrentHashMap does not has any kv,so throw such exception,but i think it should not be this while a spark-session was created.
