### ISSUE TITLE
ODBC Error while connecting to Kyuubi server

### ISSUE THREAD

**Issue by soliverr** [yaooqinn/kyuubi#180]
Every time I try to connect to Kyuubi server through ODBC driver I've got an error.

In Kyuubi log:
```
yaooqinn.kyuubi.KyuubiSQLException: Expected state FINISHED, but found RUNNING
        at yaooqinn.kyuubi.operation.KyuubiOperation.assertState(KyuubiOperation.scala:120)
        at yaooqinn.kyuubi.operation.KyuubiOperation.getNextRowSet(KyuubiOperation.scala:236)
        at yaooqinn.kyuubi.operation.OperationManager.getOperationNextRowSet(OperationManager.scala:148)
        at yaooqinn.kyuubi.session.KyuubiSession.fetchResults(KyuubiSession.scala:251)
        at yaooqinn.kyuubi.server.BackendService.fetchResults(BackendService.scala:152)
        at yaooqinn.kyuubi.server.FrontendService.FetchResults(FrontendService.scala:486)
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1553)
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1538)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at yaooqinn.kyuubi.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:46)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
On Windows host:

![dsn](https://user-images.githubusercontent.com/3872079/55956803-42ed6680-5c7e-11e9-9971-2911140d6247.png)

**Additional context**
I start Kyuubi as follows:
```
hadoop@hadoop03:/opt/kyuubi-0.6.0$ ./bin/start-kyuubi.sh --master local --deploy-mode client --conf spark.kyuubi.frontend.bind.host=192.168.1.82
Welcome to
  __  __                           __
 /\ \/\ \                         /\ \      __
 \ \ \/'/'  __  __  __  __  __  __\ \ \____/\_\
  \ \ , <  /\ \/\ \/\ \/\ \/\ \/\ \\ \ '__`\/\ \
   \ \ \\`\\ \ \_\ \ \ \_\ \ \ \_\ \\ \ \L\ \ \ \
    \ \_\ \_\/`____ \ \____/\ \____/ \ \_,__/\ \_\
     \/_/\/_/`/___/> \/___/  \/___/   \/___/  \/_/
                /\___/
                \/__/
Kyuubi Server: jar founded: /opt/kyuubi-0.6.0/lib/kyuubi-server-0.6.0.jar
starting yaooqinn.kyuubi.server.KyuubiServer, logging to /opt/kyuubi-0.6.0/logs/kyuubi-hadoop-yaooqinn.kyuubi.server.KyuubiServer-1-hadoop03.out
```

With `beeline` it works perfectly.

What I missed?

**Comment by yaooqinn** [comment]
could you help me find out the root cause？And submit an pull
request . I don't have such an ODBC scenario. Thanks very much.

**Comment by soliverr** [comment]
In a check phase, ODBC driver sends to Thrift Server command 'set -v' and expects a list of parameters.

I found in kyuubi log two kind of errors:
```019-04-12 17:28:30 INFO  KyuubiOperation:33 - Running query 'set -v' with c4737e98-e74e-407d-92b4-9e513bbd8f88
2019-04-12 17:28:30 WARN  FrontendService:42 - Error fetching results: 
yaooqinn.kyuubi.KyuubiSQLException: Expected state FINISHED, but found PENDING
```
and
```
2019-04-12 14:22:31 INFO  KyuubiOperation:33 - Running query 'set -v' with 93ee9434-5c26-4e05-87dc-2c3e837d0d0f
2019-04-12 14:22:31 INFO  KyuubiSparkUtil$:33 - Application local-1555060950488 has been activated
2019-04-12 14:22:32 WARN  FrontendService:42 - Error fetching results: 
yaooqinn.kyuubi.KyuubiSQLException: Expected state FINISHED, but found RUNNING
```

I don't quite understand the logic of Kyuubi yet, but i gues it is something wrong with `ExecuteStatement`. For some reasons, `set -v` query is not finishing when `FetchResults` occurs.

I'll try to figure it out further.

**Comment by AngersZhuuuu** [comment]
The root case is that ODBC server  work different from Beeline,  when i match it with hue, we meet same problem. Since kyuubi less some code about background operation status judge.

**Comment by soliverr** [comment]
It works:

![snapshot_2019-06-06_15:26:21_odbc](https://user-images.githubusercontent.com/3872079/59026395-bcb16300-886f-11e9-9ed5-2092fa5b8502.png)

Thank you very much. I will test Kyuubi server through ODBC further :-)

**Comment by yaooqinn** [comment]
@soliverr you are welcome. Also it would be great if you can add some docs about odbc usages. Thanks！
