### ISSUE TITLE
Caused by: java.io.IOException: Filesystem closed 	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:892)

### ISSUE THREAD

**Issue by wydhcws** [yaooqinn/kyuubi#243]
After installing kyuubi and running, everything was normal when I entered beeline for the first time; but after the second time I entered beeline to run sql again, it would report this error;
and if I kill the  kyuubi's spark job  on yarn and   entered beeline again, that's ok when I entered beeline  for the first time

20/09/16 14:17:51 ERROR scheduler.AsyncEventQueue: Listener EventLoggingListener threw an exception
java.io.IOException: Filesystem closed
Caused by: java.io.IOException: Filesystem closed 	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:892)

**Comment by wydhcws** [comment]
ok  I find the similar issue  https://github.com/yaooqinn/kyuubi/issues/137
