### ISSUE TITLE
请问我启动client的时候debug反复打印日志连接zk，最后出现失败信息,查看zk的目录，没有任何kyuubi相关的信息注册进去

### ISSUE THREAD

**Issue by MargeDog** [yaooqinn/kyuubi#252]
2020-11-18 15:45:26.729 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 52,12  replyHeader:: 52,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:27.731 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 53,12  replyHeader:: 53,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:28.733 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 54,12  replyHeader:: 54,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:29.734 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 55,12  replyHeader:: 55,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:30.737 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 56,12  replyHeader:: 56,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:31.739 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 57,12  replyHeader:: 57,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:32.740 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 58,12  replyHeader:: 58,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:33.742 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 59,12  replyHeader:: 59,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:34.744 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 60,12  replyHeader:: 60,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:35.746 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 61,12  replyHeader:: 61,51539610727,-101  request:: '/kyuubi-anonymous,F  response:: v{} 
2020-11-18 15:45:36.850 DEBUG imps.CuratorFrameworkImpl: Closing
2020-11-18 15:45:36.852 DEBUG curator.CuratorZookeeperClient: Closing
2020-11-18 15:45:36.852 DEBUG curator.ConnectionState: Closing
2020-11-18 15:45:36.854 DEBUG zookeeper.ZooKeeper: Closing session: 0x100edfdd23b005a
2020-11-18 15:45:36.854 DEBUG zookeeper.ClientCnxn: Closing client for session: 0x100edfdd23b005a
2020-11-18 15:45:36.879 DEBUG zookeeper.ClientCnxn: Reading reply sessionid:0x100edfdd23b005a, packet:: clientPath:null serverPath:null finished:false header:: 62,-11  replyHeader:: 62,51539610728,0  request:: null response:: null
2020-11-18 15:45:36.879 DEBUG zookeeper.ClientCnxn: Disconnecting client for session: 0x100edfdd23b005a
2020-11-18 15:45:36.880 INFO zookeeper.ZooKeeper: Session: 0x100edfdd23b005a closed
2020-11-18 15:45:36.880 INFO zookeeper.ClientCnxn: EventThread shut down
2020-11-18 15:45:36.882 WARN service.FrontendService: Error opening session: 
org.apache.kyuubi.KyuubiSQLException: Error opening session SessionHandle [5d8dd47d-ef7e-4b7d-9d28-c62d91a1d994] for anonymous due to Timed out(60000 ms) to launched Spark with /home/mahao/spark-3.0.1-bin-hadoop-3.1.3/bin/spark-submit --class org.apache.kyuubi.engine.spark.SparkSQLEngine --conf spark.kyuubi.hadoop.authentication=KERBEROS --conf spark.kyuubi.frontend.bind.port=10009 --conf spark.hive.server2.thrift.resultset.default.fetch.size=1000 --conf spark.kyuubi.ha.zookeeper.namespace=kyuubi --conf spark.kyuubi.ha.zookeeper.quorum=x:2181,x:2181,x:2181 --conf spark.master=yarn --conf spark.kyuubi.ha.zookeeper.acl.enabled=true --proxy-user anonymous /home/mahao/kyuubi/externals/engines/spark/kyuubi-spark-sql-engine-1.0.0-SNAPSHOT.jar
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:48)
        at org.apache.kyuubi.session.KyuubiSessionManager.openSession(KyuubiSessionManager.scala:68)
        at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:39)
        at org.apache.kyuubi.service.FrontendService.getSessionHandle(FrontendService.scala:176)

**Comment by yaooqinn** [comment]
spark.kyuubi.ha.zookeeper.quorum=x:2181,x:2181,x:2181

**Comment by MargeDog** [comment]
> spark.kyuubi.ha.zookeeper.quorum=x:2181,x:2181,x:2181

我的host配置是正确的，x只是马赛克效果啦，😂，不过，我发现没有开启kyuubi的kerber的时候提交卡在zk这里，
当我开启kerberos时候，启动kyuubi就会认证本地的系统用户，没办法获取我当前的klist用户么？

**Comment by yaooqinn** [comment]
刚好你卡在这里的话，提个PR fix 吧？我还没测试这块

**Comment by MargeDog** [comment]
@yaooqinn 我还在看你的代码，前些天在测试你的spark-ranger的项目，同事修改了代码通过的spark3.0的测试，想问下你有这两个相关项目的微信群或者其他的交流地方么？
