### ISSUE TITLE
kyuubi-1.0.0-SNAPSHOT-bin-spark-3.0.1 KyuubiSQLException

### ISSUE THREAD

**Issue by yuangjiang** [yaooqinn/kyuubi#257]
org.apache.kyuubi.KyuubiSQLException: Error opening session SessionHandle [446b1896-5406-43bf-8658-3b33ac3275fe] for anonymous due to Error: A fatal exception has occurred. Program will exit.
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:48)
	at org.apache.kyuubi.session.KyuubiSessionManager.openSession(KyuubiSessionManager.scala:68)
	at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:39)
	at org.apache.kyuubi.service.FrontendService.getSessionHandle(FrontendService.scala:176)
	at org.apache.kyuubi.service.FrontendService.OpenSession(FrontendService.scala:185)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1377)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1362)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kyuubi.KyuubiSQLException: Error: A fatal exception has occurred. Program will exit.
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:54)
	at org.apache.kyuubi.engine.ProcBuilder$$anon$1.run(ProcBuilder.scala:80)
	... 1 more

**Comment by yaooqinn** [comment]
you can check the spark process log to see what's going on,  the dir `work` is where it locates
