### ISSUE TITLE
CDH 6.3.1 HUE can not list database

### ISSUE THREAD

**Issue by pan3793** [yaooqinn/kyuubi#280]
**Describe the bug**
CDH 6.3.1 HUE can not list database

**To Reproduce**
1. Configurations
2. Environments
  - CDH 6.3.1 HUE
  - Kyuubi master code
  - Spark 3.0.1
3. Operations

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/26535726/104452823-7fca5800-55de-11eb-8cc3-f866d13090a0.png)

**Additional context**

```
2021-01-13 20:29:29.276 DEBUG service.FrontendService: TGetSchemasReq(sessionHandle:TSessionHandle(sessionId:THandleIdentifier(guid:B9 D7 B7 A2 56 3F 4A BE 9D 6A EA 69 4F 79 F6 F2, secret:19 A6 9A 9C 9B 61 4D 74 8B C1 46 70 3C 86 95 C8)), schemaName:*)
2021-01-13 20:29:29.276 INFO operation.GetSchemas: Processing bigdata's query[6ec6f36a-5d76-43d7-8e39-47a1f9930c18]: INITIALIZED_STATE -> RUNNING_STATE, statement: GET_SCHEMAS
2021-01-13 20:29:29.282 INFO operation.GetSchemas: Processing bigdata's query[6ec6f36a-5d76-43d7-8e39-47a1f9930c18]: RUNNING_STATE -> ERROR_STATE, statement: GET_SCHEMAS, time taken: 0.006 seconds
2021-01-13 20:29:29.283 WARN service.FrontendService: Error getting schemas:
org.apache.kyuubi.KyuubiSQLException: Error operating GET_SCHEMAS: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*
^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.sequence(Pattern.java:2125)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.apache.kyuubi.engine.spark.operation.GetSchemas.runInternal(GetSchemas.scala:48)
	at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:127)
	at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:91)
	at org.apache.kyuubi.session.AbstractSession.getSchemas(AbstractSession.scala:156)
	at org.apache.kyuubi.service.AbstractBackendService.getSchemas(AbstractBackendService.scala:84)
	at org.apache.kyuubi.service.FrontendService.GetSchemas(FrontendService.scala:291)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1497)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1482)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:51)
	at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:96)
	at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:87)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.kyuubi.engine.spark.operation.GetSchemas.runInternal(GetSchemas.scala:54)
	at org.apache.kyuubi.operation.AbstractOperation.run(AbstractOperation.scala:127)
	at org.apache.kyuubi.session.AbstractSession.runOperation(AbstractSession.scala:91)
	at org.apache.kyuubi.session.AbstractSession.getSchemas(AbstractSession.scala:156)
	at org.apache.kyuubi.service.AbstractBackendService.getSchemas(AbstractBackendService.scala:84)
	at org.apache.kyuubi.service.FrontendService.GetSchemas(FrontendService.scala:291)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1497)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1482)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.regex.PatternSyntaxException:Dangling meta character '*' near index 0
*
^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.sequence(Pattern.java:2125)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.apache.kyuubi.engine.spark.operation.GetSchemas.runInternal(GetSchemas.scala:48)
```

**Comment by pan3793** [comment]
After some investigation, found the root cause seed a `TGetSchemasReq` with parameter `schemaName:*` which not match  SQL standard.

**Comment by yaooqinn** [comment]
nice catch~
