### ISSUE TITLE
SparkIcebergOperationSuite failed: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Yikun** [yaooqinn/kyuubi#496]
### 1. Describe the bug

build/mvn clean package -pl :kyuubi-spark-sql-engine -Pspark-3.2-snapshot

```
SparkIcebergOperationSuite:
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: org.apache.spark.sql.internal.VariableSubstitution.<init>(Lorg/apache/spark/sql/internal/SQLConf;)V
  at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.substitutor$lzycompute(IcebergSparkSqlExtensionsParser.scala:39)
  at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.substitutor(IcebergSparkSqlExtensionsParser.scala:39)
  at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:96)
  at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:615)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
  at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:774)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:612)
  at org.apache.kyuubi.engine.spark.SparkSQLEngine$.$anonfun$createSpark$4(SparkSQLEngine.scala:99)
  at org.apache.kyuubi.engine.spark.SparkSQLEngine$.$anonfun$createSpark$4$adapted(SparkSQLEngine.scala:99)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2021-04-08T23:11:36+08:00
[INFO] ------------------------------------------------------------------------
```

[1] https://github.com/yaooqinn/kyuubi/pull/495/checks?check_run_id=2297817023#step:8:10492

#### 2.1 Versions

- Kyuubi
  - [x] 1.1.0

- Spark
  - [x] 3.2.x

### 3. Steps to reproduce

checkout https://github.com/yaooqinn/kyuubi/pull/495/

build/mvn clean package -pl :kyuubi-spark-sql-engine -Pspark-3.2-snapshot

**Comment by yaooqinn** [comment]
this is a bit hacky for apache iceberg to call an internal API of Spark, we have a tag for these test, which we could use them to exclude them

**Comment by Yikun** [comment]
I guess something like `-Dmaven.plugin.scalatest.exclude.tags=org.apache.kyuubi.tags.DataLakeTest`, will have a try
