### ISSUE TITLE
Delegation Token can be issued only with kerberos or web authentication

### ISSUE THREAD

**Issue by yaooqinn** [yaooqinn/kyuubi#98]
**Describe the bug**

```
18/08/22 11:58:11 INFO KyuubiOperation: Running query 'select * from src2' with 35d721c7-9e8f-4f59-ac37-eac2b230a2e3
18/08/22 11:58:11 INFO SparkSqlParser: Parsing command: select * from src2
18/08/22 11:58:11 INFO CatalystSqlParser: Parsing command: int
18/08/22 11:58:11 INFO CatalystSqlParser: Parsing command: string
18/08/22 11:58:11 INFO deprecation: mapred.map.tasks is deprecated. Instead, use mapreduce.job.maps
18/08/22 11:58:11 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 344.3 KB, free 15.8 GB)
18/08/22 11:58:12 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 31.2 KB, free 15.8 GB)
18/08/22 11:58:12 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.201.168.184:57704 (size: 31.2 KB, free: 15.8 GB)
18/08/22 11:58:12 INFO SparkContext: Created broadcast 0 from toString at KyuubiOperation.scala:319
18/08/22 11:58:12 INFO GPLNativeCodeLoader: Loaded native gpl library
18/08/22 11:58:12 WARN LzoCompressor: java.lang.UnsatisfiedLinkError: Cannot load liblzo2.so.2 (liblzo2.so.2: cannot open shared object file: No such file or directory)!
18/08/22 11:58:12 ERROR LzoCodec: Failed to load/initialize native-lzo library
18/08/22 11:58:12 ERROR KyuubiOperation:
Error executing query as hzyaoqin,
select * from src2
Current operation state RUNNING,
org.apache.hadoop.ipc.RemoteException(java.io.IOException): Delegation Token can be issued only with kerberos or web authentication
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getDelegationToken(FSNamesystem.java:6648)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getDelegationToken(NameNodeRpcServer.java:564)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getDelegationToken(ClientNamenodeProtocolServerSideTranslatorPB.java:987)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)

        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy12.getDelegationToken(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDelegationToken(ClientNamenodeProtocolTranslatorPB.java:933)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy13.getDelegationToken(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getDelegationToken(DFSClient.java:1030)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getDelegationToken(DistributedFileSystem.java:1543)
        at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:532)
        at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:510)
        at org.apache.hadoop.hdfs.DistributedFileSystem.addDelegationTokens(DistributedFileSystem.java:2228)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:121)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:206)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:202)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
```

**To Reproduce**
1. Configurations
2. Environments
3. Operations

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cxzl25** [comment]
If multiple threads share the same ugi without using impersonation, is it possible to trigger this exception?
https://github.com/yaooqinn/kyuubi/blob/master/kyuubi-server/src/main/scala/yaooqinn/kyuubi/session/KyuubiSession.scala#L85

**Comment by yaooqinn** [comment]
Thanks @cxzl25 , the case I ran into the exception was using impersonation. Recent versions of Kyuubi seems to have no such a problem.

**Comment by cxzl25** [comment]
I encountered this problem a few months ago when I was using impersonation.This problem was solved not long ago.
BTW, apply different tokens for the same user's different session, so that does not cause a lot of tokens in the namenode?
https://github.com/yaooqinn/kyuubi/blob/master/kyuubi-server/src/main/scala/yaooqinn/kyuubi/session/KyuubiSession.scala#L79
